apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-weql
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0013-tenant/ci1t-830-0013-app/devfile-sample-weql@sha256:196a4acc5682e8eea8264ca35a7fb7d209fbfb903b6827a0be7a2553c8d81ee5
        name: my-nodejs
        resources: {}
status: {}
